#pragma config(Sensor, dgtl1,  BtnForward,     sensorTouch)
#pragma config(Sensor, dgtl2,  BtnBack,        sensorTouch)
#pragma config(Motor,  port2,           LeftSideTop,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LeftSideBottom, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           RightSideTop,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           RightSideBottom, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           left_drive_motor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           right_drive_motor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"
#include "Drive.h"
#include "Ian_Fly_Wheel.h"
#include "TestMoveLauncher.h"

void pre_auton()
{

}

task autonomous()
{
	AutonomousCodePlaceholderForTesting();
}

task usercontrol()
{
	while (true)
	{
		updateDrive();
		variables();
		fullFlyWheelIsTrue(vexRT[Btn6D], vexRT[Btn6U]);
		halfFlyWheelIsTrue(vexRT[Btn5D], vexRT[Btn5U]);
		launchFullFlyWheel();
		launchHalfFlyWheel();
		testShoot(vexRT[Ch2], vexRT[Ch4]);
	}
}
//updated on 10/29/2015, inverted left bottom and right top. changed return value for boolean function Updated by: Juyeong Lee
