#pragma config(Motor,  port2,           leftTopLauncher, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftBottomLauncher, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rightTopLauncher, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightBottomLauncher, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           leftDriveMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           rightDriveMotor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"
#include "IanDrive.h"
#include "IanFlyWheel.h"

void pre_auton()
{
  bStopTasksBetweenModes = true;
}

task autonomous()
{
	AutonomousCodePlaceholderForTesting();
}

task usercontrol()
{

	while (true)
	{
		drive();
	}
}
