#pragma config(Motor,  port2,           leftTopLauncher, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftBottomLauncher, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightTopLauncher, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           rightBottomLauncher, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightDriveMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftDriveMotor, tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"
#include "IanDrive.h"
#include "IanFlyWheel.h"
#include "IanFlyBot2.h"

void pre_auton()
{
  bStopTasksBetweenModes = true;
}

task autonomous()
{
	AutonomousCodePlaceholderForTesting();
}

task usercontrol()
{

	while (true)
	{
		setForwardValue(vexRT[Ch2]);
		setTurnValue(vexRT[Ch1]);
		drive();

		//fullFlyWheel(vexRT[Btn5U]);
		//halfFlyWheel(vexRT[Btn6U]);

		setFullFlyWheel(vexRT[Btn5U]);
		setFullFlyWheelOff(vexRT[Btn5D]);
		setHalfFlyWheel(vexRT[Btn6U]);
		setHalfFlyWheelOff(vexRT[Btn6D]);

		fullFlyWheel();
		halfFlyWheel();
	}
}

//updated on 11/09/2015, added Intake file
//Updated by: Juyeong Lee
