#pragma config(Motor,  port2,           leftTopLauncher, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftBottomLauncher, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           rightTopLauncher, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           rightBottomLauncher, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           rightDriveMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           leftDriveMotor, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           wheelIntakeMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          railIntakeMotor, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
//Sets port for motors

//All default should not be deleted at all!
#pragma platform(VEX)//default

//Competition Control and Duration Settings, default
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

//including all file that are needed, default
#include "Vex_Competition_Includes.c"
#include "IanDrive.h"
//#include "IanFlyWheel.h"
#include "IanFlyBot2.h"

void pre_auton() //pre-autonomous code
{
  bStopTasksBetweenModes = true; //auto generated code
}

task autonomous() //autonomous code
{
	AutonomousCodePlaceholderForTesting(); //filler code
}

task usercontrol()//user control code
{

	while (true) //Do not touch this code - is necessary in order to run the code
	{
		//set motor value
		setForwardValue(vexRT[Ch2]); //sets forward value of drive to y axis joystick
		setTurnValue(vexRT[Ch1]); //sets "turn" value of drive to x axis joystick

		//activates drive function
		drive();

		//fullFlyWheel(vexRT[Btn5U]); Code for the manual launcher - has to press it to continue launching -
		//halfFlyWheel(vexRT[Btn6U]);

		//set up for FlyWheel Function
		setFullFlyWheel(vexRT[Btn5U]); //moves the launcher with full speed (when 5U is pressed)
		setFullFlyWheelOff(vexRT[Btn5D]); //stops the launcher(full) (when 5D is pressed)
		setHalfFlyWheel(vexRT[Btn6U]); //moves the launcher with half of the speed (when 6U is pressed)
		setHalfFlyWheelOff(vexRT[Btn6D]); //stops the launcher(half) (when 6D is pressed)

		//activates the FlyWheel Function
		fullFlyWheel(); //launcher moves with full speed
		halfFlyWheel(); //launcher moves with half of the speed
	}
}

//Updated on 11/18/2015, adding two motor for the intake roller
//Updated by: Juyeong Lee
